// Questões transcritas/adaptadas minimamente do Estudo Dirigido enviado pelo usuário.
// Mantemos a formulação próxima ao material e acrescentamos comentários didáticos.
const DIGITAL_QUESTIONS = [
['Internet e Web','Qual é a diferença entre Internet e Web?',['A Internet é o sistema de páginas e a Web são os cabos.','São nomes diferentes para a mesma coisa.','A Internet é a infraestrutura de conexão e a Web é o sistema de páginas e links que acessamos.','A Web surgiu antes da Internet.'],2,'A Internet é a grande rede que conecta computadores e dispositivos. A Web é um serviço que funciona sobre essa rede, formado por páginas, sites e links acessados pelo navegador.'],
['Internet e Web','Tim Berners-Lee é o cientista que criou a World Wide Web (WWW) em 1989.',['Verdadeiro','Falso'],0,'Verdadeiro. Tim Berners-Lee propôs a World Wide Web em 1989. A Web facilitou o acesso a documentos ligados por hiperlinks através da Internet.'],
['Internet no Brasil','A internet chegou oficialmente ao Brasil no ano de 1988, começando dentro das universidades.',['Verdadeiro','Falso'],0,'Verdadeiro, conforme o estudo dirigido. As primeiras conexões brasileiras ligadas à Internet ocorreram no ambiente acadêmico e de pesquisa.'],
['Redes LAN e WAN','Como chamamos a rede que conecta computadores em um local pequeno, como uma casa ou uma sala de aula?',['WAN (Rede Mundial).','LAN (Rede Local).','Bluetooth.','Satélite.'],1,'LAN significa Local Area Network, ou Rede Local. Ela conecta dispositivos em uma área limitada, como uma casa, escola, laboratório ou escritório.'],
['Redes LAN e WAN','A rede WAN é usada para conectar dispositivos e redes a grandes distâncias, como acontece na própria Internet.',['Verdadeiro','Falso'],0,'Verdadeiro. Uma WAN cobre áreas geográficas grandes e pode interligar várias redes locais. A Internet é o maior exemplo de rede de alcance mundial.'],
['Topologias','Na topologia de rede em ESTRELA, como os computadores são conectados?',['Todos são ligados em um único cabo comprido.','Eles formam um círculo fechado.','Todos os aparelhos se conectam a um ponto central.','Não existe conexão entre eles.'],2,'Na topologia em estrela, cada dispositivo se liga a um equipamento central, normalmente um switch. Assim, as conexões partem do centro como os raios de uma estrela.'],
['Topologias','Na topologia em BARRAMENTO, todos os dispositivos usam um único cabo principal para transmitir dados.',['Verdadeiro','Falso'],0,'Verdadeiro. No barramento, existe um cabo principal compartilhado pelos dispositivos. É justamente esse formato que dá nome à topologia.'],
['Equipamentos de rede','Qual destes aparelhos é responsável por distribuir o sinal de internet sem fio (Wi-Fi) na nossa casa?',['Hub.','Switch.','Roteador.','Impressora.'],2,'O roteador encaminha o tráfego entre redes e, nos modelos domésticos com Wi-Fi, também permite que celulares, computadores e outros aparelhos se conectem sem fio.'],
['Equipamentos de rede','O “Switch” é um equipamento mais simples que o “Hub” e não consegue gerenciar a rede.',['Verdadeiro','Falso'],1,'Falso. O switch é mais inteligente que o hub para encaminhar dados dentro da rede: ele aprende os endereços dos dispositivos e envia os quadros à porta adequada, enquanto o hub simplesmente repete o sinal.'],
['Endereço IP','O que é o Endereço IP?',['É a senha do Wi-Fi.','É o nome que escolhemos para o computador.','É um endereço numérico usado para identificar um dispositivo em uma rede IP.','É o nome do navegador de internet.'],2,'O endereço IP funciona como um endereço de comunicação na rede. Ele permite identificar interfaces/dispositivos e ajuda os dados a chegarem ao destino correto.'],
['Endereço IP','O modelo IPv6 foi criado porque os endereços disponíveis no antigo IPv4 estavam se esgotando com o grande aumento de aparelhos conectados.',['Verdadeiro','Falso'],0,'Verdadeiro. O IPv4 possui um espaço limitado de endereços. O IPv6 foi desenvolvido com um espaço de endereçamento muito maior, adequado ao crescimento da Internet.'],
['HTTP e HTTPS','Qual é a função do protocolo HTTP na internet?',['Permitir a comunicação e transferência de recursos da Web, como textos, imagens, áudios e vídeos.','Proteger o computador contra quedas de energia.','Aumentar o som do computador.','Criar senhas automáticas para o e-mail.'],0,'HTTP é o protocolo usado na comunicação entre navegador e servidor para solicitar e entregar recursos da Web. Ele permite carregar páginas e conteúdos como textos e imagens.'],
['HTTP e HTTPS','Quando vemos HTTPS no navegador, o que isso significa?',['Que o site é proibido para menores.','Que a comunicação entre navegador e site usa criptografia.','Que o Wi-Fi está quebrado.','Que o site é muito lento.'],1,'HTTPS é a versão protegida do HTTP. Ele usa criptografia para proteger os dados durante a comunicação entre o navegador e o servidor. Isso não significa, sozinho, que todo conteúdo do site seja confiável.'],
['Web','A parte da internet que acessamos por mecanismos de busca e sites públicos é chamada de Surface Web e representa quase tudo o que existe na rede.',['Verdadeiro','Falso'],1,'Falso. A Surface Web é a parte publicamente acessível e normalmente indexada por mecanismos de busca, mas não corresponde a tudo o que existe na Internet/Web. Há muito conteúdo que não é indexado publicamente.'],
['Cidadania digital','Espalhar notícias falsas (fake news) ou ofender pessoas na internet é uma violação dos nossos deveres digitais.',['Verdadeiro','Falso'],0,'Verdadeiro. Cidadania digital também envolve responsabilidade: verificar informações antes de compartilhar, respeitar outras pessoas e usar os ambientes digitais de forma ética.'],
['Cidadania digital','O que são Direitos Digitais?',['A obrigação de pagar a conta da internet.','Liberdades e garantias, como privacidade e acesso à informação.','O direito de baixar filmes piratas.','O direito de usar o celular durante as aulas.'],1,'Direitos digitais são direitos aplicados ao ambiente digital. Entre os exemplos trabalhados no estudo estão privacidade e acesso à informação. Eles vêm acompanhados de deveres e responsabilidades.'],
['Privacidade','O respeito à privacidade significa que ninguém deve acessar ou divulgar nossas informações pessoais sem permissão.',['Verdadeiro','Falso'],0,'Verdadeiro como regra de respeito e segurança digital. Informações pessoais devem ser tratadas com cuidado e não devem ser expostas indevidamente.'],
['Tecnologias assistivas','Ferramentas como o NVDA (leitor de tela) e o Hand Talk (tradutor de Libras) são exemplos de tecnologias assistivas para acessibilidade digital.',['Verdadeiro','Falso'],0,'Verdadeiro. Tecnologias assistivas ajudam a reduzir barreiras de acesso. O NVDA pode ler o conteúdo da tela, enquanto o Hand Talk oferece recursos de tradução para Libras.'],
['Fibra óptica','Como a fibra óptica transmite os dados da internet de forma tão rápida?',['Através de sinais de fumaça.','Usando fios de cobre com eletricidade.','Através de pulsos de luz dentro de fibras de vidro ou plástico.','Usando apenas o som.'],2,'A fibra óptica transporta informações por pulsos de luz que percorrem fibras muito finas de vidro ou plástico. Isso permite transmitir grande quantidade de dados com alta velocidade.'],
['Wi-Fi','O Wi-Fi utiliza ondas de rádio para conectar aparelhos sem precisar de cabos entre eles.',['Verdadeiro','Falso'],0,'Verdadeiro. O Wi-Fi usa ondas de rádio para a comunicação sem fio entre o dispositivo e o ponto de acesso/roteador. A conexão da rede com a Internet pode usar outros meios, como fibra óptica.'],
['GPS e satélites','Como o sistema de GPS consegue calcular nossa localização na Terra?',['Tirando fotos de todos os prédios.','Através de sinais enviados por uma rede de satélites no espaço.','Através dos cabos submarinos.','O GPS só funciona perto de uma antena de rádio.'],1,'O receptor de GPS recebe sinais de vários satélites e usa informações de tempo e distância para calcular sua posição. Quanto mais sinais adequados recebe, melhor pode determinar a localização.'],
['Satélites','A Lua é um exemplo de satélite natural da Terra.',['Verdadeiro','Falso'],0,'Verdadeiro. A Lua é o satélite natural da Terra. Já os satélites artificiais são construídos e lançados pelo ser humano para funções como comunicação, localização e observação.'],
['Data Centers','O que é um Data Center (ou CPD)?',['Uma loja que vende celulares.','Um local físico com muitos servidores que armazenam e processam dados.','Um tipo de satélite meteorológico.','O nome de um novo navegador.'],1,'Um Data Center é uma instalação preparada para abrigar servidores e equipamentos de rede. Esses computadores armazenam, processam e disponibilizam dados e serviços digitais.'],
['Data Centers','Dentro de um Data Center, o resfriamento constante é importante porque os servidores geram muito calor ao funcionar sem parar.',['Verdadeiro','Falso'],0,'Verdadeiro. Servidores e outros equipamentos eletrônicos produzem calor. Sistemas de refrigeração ajudam a manter a temperatura adequada e evitam superaquecimento e falhas.'],
['Nuvem','Onde ficam guardados fisicamente os arquivos, como fotos e vídeos, que salvamos na “nuvem”?',['Flutuando no ar.','Dentro dos satélites artificiais.','Em sistemas de armazenamento ligados a servidores físicos em Data Centers.','Apenas no cartão de memória do celular.'],2,'“Nuvem” não significa que os arquivos ficam no ar. Os dados são armazenados em equipamentos físicos, normalmente distribuídos em Data Centers, e acessados pela rede.'],
['Energia em Data Centers','O sistema UPS, também chamado de nobreak, ajuda a manter os servidores funcionando quando há uma interrupção de energia elétrica.',['Verdadeiro','Falso'],0,'Verdadeiro. O UPS/nobreak fornece energia temporária quando a alimentação principal falha, ajudando a evitar desligamentos imediatos e permitindo a continuidade ou o desligamento seguro dos equipamentos.'],
['Navegadores','Qual destes softwares é um exemplo de navegador (browser)?',['WhatsApp.','Google Chrome.','Instagram.','Roblox.'],1,'Google Chrome é um navegador: um programa usado para abrir e navegar por páginas e aplicações da Web. WhatsApp, Instagram e Roblox têm outras funções principais.'],
['Links','O “Link” é como uma ponte que nos leva de uma página para outra na internet quando clicamos nele.',['Verdadeiro','Falso'],0,'Verdadeiro. Um link, ou hiperlink, é um elemento que aponta para outro recurso, como outra página, arquivo ou parte de um site. Ao acioná-lo, o navegador segue esse endereço.'],
['Pacotes de dados','Como os dados viajam pela internet até chegar ao destino?',['Como um arquivo gigante e pesado de uma vez só.','Por meio de cartas enviadas pelo correio.','São divididos em pequenas partes chamadas “pacotes de dados”.','Eles viajam apenas por ondas magnéticas do Sol.'],2,'Os dados transmitidos em redes são divididos em unidades menores chamadas pacotes. Esses pacotes podem percorrer a rede e são processados no destino para que a informação seja utilizada.']
];
DIGITAL_QUESTIONS.forEach(([topic,stem,options,answer,explanation])=>QUESTIONS.push({subject:'Educação Digital',topic,stem,options,answer,explanation}));
