const facts={
'Inglês':[
['Possessive Adjectives','Qual afirmação sobre possessive adjectives está correta?','Concordam com o possuidor e vêm antes de um substantivo.','Os adjetivos possessivos concordam com o possuidor e acompanham um substantivo.'],
['Possessive Adjectives','Complete corretamente: “She loves ___ job.”','her','Her é o adjetivo possessivo ligado a she.'],
['Possessive Adjectives','Complete corretamente: “We sold ___ car last week.”','our','Our é o adjetivo possessivo de we.'],
['Possessive Adjectives','Complete corretamente: “They forgot ___ passports at home.”','their','Their acompanha passports e se refere a they.'],
['Possessive Adjectives','Em “The dog is chasing its tail”, “its” é:','um adjetivo possessivo referente ao animal','Its funciona como adjetivo possessivo antes de tail.'],
['Possessive Pronouns','Qual afirmação sobre possessive pronouns está correta?','Substituem substantivos ou frases nominais para evitar repetição.','Os pronomes possessivos podem aparecer sem substantivo.'],
['Possessive Pronouns','Complete: “This jacket is ___, not yours.”','mine','Mine substitui “my jacket”.'],
['Possessive Pronouns','Em “Her house is big, but ours is bigger”, “ours” substitui:','our house','Ours substitui “our house”.'],
['Possessive Pronouns','Qual par está corretamente relacionado?','My → Mine','My é adjetivo possessivo e mine é pronome possessivo.'],
['Possessive Pronouns','Em “Is it yours?”, “yours” funciona porque:','pode funcionar sozinho, substituindo a expressão possessiva','Yours é pronome possessivo.'],
['Genitive Case','A estrutura geral do Genitive Case no singular é:','substantivo + ’s + objeto possuído','Essa é a estrutura geral apresentada no material.'],
['Genitive Case','Como indicar corretamente “o carro de Mary”?','Mary’s car','Mary é singular e recebe ’s.'],
['Genitive Case','Para plural terminado em -s, deve-se:','adicionar apenas o apóstrofo','Em plurais terminados em s, adiciona-se apenas o apóstrofo.'],
['Genitive Case','Como escrever “o quarto dos meninos”?','The boys’ room','Boys é plural terminado em s.'],
['Genitive Case','Como escrever “os brinquedos das crianças”?','The children’s toys','Children é plural irregular e recebe ’s.'],
['Genitive Case','Para coisas inanimadas, geralmente se prefere:','a construção com of','O material prefere of para objetos/coisas inanimadas.'],
['Genitive Case','Qual construção é preferível para “a porta da casa”?','The door of the house','Esse é o exemplo apresentado no material.'],
['Genitive Case','Para Charles, quais formas são aceitas no material?','Charles’s e Charles’','O material aceita as duas formas.'],
['Genitive Case','Em posse compartilhada por Sarah e John, usa-se:','Sarah and John’s apartment','Na posse compartilhada, o ’s aparece no último nome.'],
['Revisão','Qual diferença entre my e mine está correta?','My acompanha substantivo; mine pode substituí-lo.','My é adjetivo possessivo; mine é pronome possessivo.']],
'História':[
['Grécia Antiga','A Grécia Antiga era formada principalmente por:','cidades-estado independentes chamadas pólis','O material define a Grécia como conjunto de pólis independentes.'],
['Grécia Antiga','Os gregos identificavam-se como helenos porque compartilhavam:','língua, religião e traços culturais','As pólis compartilhavam elementos culturais.'],
['Grécia Antiga','Uma característica intelectual destacada foi:','a busca de explicações racionais, o Logos','O material destaca explicações racionais.'],
['Grécia Antiga','O Partenon foi erguido em:','Atenas, dedicado a Atena','O material situa o Partenon em Atenas.'],
['Grécia Antiga','Os Jogos Olímpicos citados foram criados em:','776 a.C., em Olímpia','Essa data e local constam do material.'],
['Pólis','A pólis grega era:','uma comunidade autônoma com leis, moeda e governo próprios','A pólis possuía autonomia política.'],
['Atenas','A política ateniense é caracterizada como:','democracia direta','Atenas é apresentada como democracia direta.'],
['Esparta','A organização política de Esparta é caracterizada como:','oligarquia militar','O material caracteriza Esparta dessa forma.'],
['Atenas','Em Atenas, os cidadãos eram:','homens adultos, livres e nascidos em Atenas','Essa é a definição apresentada no material.'],
['Esparta','Os hilotas eram:','servos estatais submetidos à elite','O material define os hilotas como servos estatais.'],
['Esparta','O Agoge era:','sistema estatal de educação e treinamento militar','O Agoge treinava meninos espartíatas.'],
['Roma','O período monárquico romano indicado vai de:','753 a.C. a 509 a.C.','Essas datas constam do material.'],
['Roma','A República Romana surgiu após:','a derrubada do último rei etrusco','A transição ocorreu em 509 a.C.'],
['República Romana','Na República, destacavam-se como órgãos de poder:','Cônsules e Senado','O material destaca dois cônsules e o Senado.'],
['Sociedade Romana','Os patrícios eram:','aristocratas e grandes proprietários','Os patrícios concentravam poder político e religioso.'],
['Sociedade Romana','Os plebeus eram principalmente:','comerciantes, artesãos e camponeses, formando a maioria da população','Essa composição é explicitada no material.'],
['Conquistas Plebeias','O Tribunato da Plebe concedeu aos magistrados plebeus:','poder de veto','Os tribunos tinham poder de veto.'],
['Conquistas Plebeias','A Lei das XII Tábuas é apresentada como:','primeiro código escrito do direito romano','Essa é a caracterização do material.'],
['Conquistas Plebeias','A Lei Canuleia permitiu:','o casamento entre patrícios e plebeus','O material registra essa permissão.'],
['Conquistas Plebeias','A Lei Licínia-Sêxtia garantiu, segundo o material:','um cônsul plebeu e o fim da escravidão por dívidas para cidadãos romanos','Essas conquistas são atribuídas à lei no material.']],
'Artes':[
['Conceito de Arte','A arte é definida no material como:','forma de expressão que combina estética, sensibilidade, técnica e intelecto','Essa é a definição apresentada.'],
['Importância da Arte','A subjetividade da arte significa que:','o significado varia conforme espectador e contexto','O material relaciona subjetividade à variação de significado.'],
['Importância da Arte','A atemporalidade indica que a arte:','atravessa séculos e preserva memória','A arte pode preservar a memória humana.'],
['Importância da Arte','A função crítica e social da arte consiste em:','provocar reflexões políticas, existenciais e culturais','Essa função é destacada no material.'],
['Obras','“A Noite Estrelada”, de 1889, é obra de:','Vincent van Gogh','O material atribui a obra a Van Gogh.'],
['Obras','“Guernica”, de Pablo Picasso, retrata:','os horrores da Guerra Civil Espanhola','Essa contextualização consta do material.'],
['Arte e Cultura','Cultura abrange:','costumes, crenças, saberes e valores de um grupo social','Essa é a definição apresentada.'],
['Arte e Cultura','A identidade cultural:','conecta um povo às raízes e tradições','O material relaciona identidade cultural às raízes.'],
['Arte e Cultura','O dinamismo cultural significa que a cultura:','transforma-se à medida que a sociedade evolui','O material apresenta a cultura como dinâmica.'],
['Linguagem Visual','O ponto é:','a menor unidade da linguagem visual','O ponto é apresentado como a menor unidade.'],
['Linguagem Visual','A linha é definida como:','sequência de pontos em movimento','A linha pode criar contornos e direção.'],
['Linguagem Visual','A forma é:','espaço definido por linhas, podendo ser geométrico ou orgânico','O material diferencia formas geométricas e orgânicas.'],
['Linguagem Visual','A cor é apresentada como:','percepção da luz refletida','Essa é a definição do material.'],
['Linguagem Visual','Textura corresponde ao:','aspecto tátil ou visual de uma superfície','Pode ser áspera, lisa, macia etc.'],
['Pontoilismo','O Pontoilismo citado foi liderado por:','Georges Seurat','O material associa o movimento a Georges Seurat.'],
['Linguagens Artísticas','As artes visuais são apreciadas prioritariamente pela:','visão','Pintura, escultura, fotografia e cinema são exemplos.'],
['Música','Os três elementos centrais da música destacados são:','melodia, harmonia e ritmo','O material lista esses três elementos.'],
['Dança','A dança utiliza para comunicar intenções e sentimentos:','corpo, espaço, tempo e movimento','Esses quatro elementos aparecem no material.'],
['Teatro','O teatro envolve:','atuação, texto dramático, cenário, figurino, iluminação e sonoplastia','O material enumera esses componentes.'],
['Teatro','As máscaras teatrais gregas chamadas personas ajudavam a:','identificar personagens à distância e amplificar a voz','Essas funções são atribuídas às personas no material.']]};
const wrong={Inglês:['uma regra sem relação com posse','uma forma verbal obrigatória','uma construção que sempre exige artigo'],História:['uma instituição inexistente nesse contexto','uma característica atribuída a outro período','uma afirmação contrária ao material'],Artes:['um conceito que o material não atribui ao tema','uma definição contrária ao material','um elemento pertencente a outra linguagem artística']};
window.QUESTIONS=[];Object.entries(facts).forEach(([subject,items])=>items.forEach(([topic,stem,correct,explanation],i)=>{let options=[correct,...wrong[subject]];let shift=i%4;options=options.slice(shift).concat(options.slice(0,shift));QUESTIONS.push({subject,topic,stem,options,answer:options.indexOf(correct),explanation})}));