const facts={
'Inglês':[
['Adjetivos possessivos','Os adjetivos possessivos, como my, your e her, servem para:','mostrar a quem algo pertence','Eles indicam posse e aparecem antes de um substantivo.'],
['Adjetivos possessivos','Complete: “She loves ___ job.”','her','Usamos her quando o possuidor é she.'],
['Adjetivos possessivos','Complete: “We sold ___ car last week.”','our','Usamos our quando o possuidor é we.'],
['Adjetivos possessivos','Complete: “They forgot ___ passports at home.”','their','Usamos their quando o possuidor é they.'],
['Adjetivos possessivos','Na frase “The dog is chasing its tail”, a palavra “its” indica:','que a cauda pertence ao cachorro','Its é usado para indicar posse de uma coisa ou animal.'],
['Pronomes possessivos','Os pronomes possessivos, como mine e yours, são usados para:','indicar posse sem repetir o substantivo','Eles podem aparecer sozinhos, evitando repetir palavras.'],
['Pronomes possessivos','Complete: “This jacket is ___, not yours.”','mine','Mine significa “minha” nesse exemplo e aparece sem repetir jacket.'],
['Pronomes possessivos','Na frase “Her house is big, but ours is bigger”, “ours” quer dizer:','our house','Ours substitui “our house”.'],
['Pronomes possessivos','Qual combinação está correta?','My → Mine','My acompanha um substantivo; mine pode aparecer sozinho.'],
['Pronomes possessivos','Na pergunta “Is it yours?”, a palavra “yours”:','indica posse e pode aparecer sozinha','Yours é um pronome possessivo.'],
['Caso genitivo','Para mostrar que algo pertence a uma pessoa, podemos usar:','nome + ’s + objeto','Exemplo: Peter’s car, isto é, o carro de Peter.'],
['Caso genitivo','Como escrever “o carro de Mary” em inglês?','Mary’s car','O ’s depois de Mary mostra que o carro pertence a ela.'],
['Caso genitivo','Quando uma palavra no plural já termina em s, como boys, usamos:','apenas o apóstrofo depois do s','Por isso escrevemos boys’ room.'],
['Caso genitivo','Como escrever “o quarto dos meninos”?','The boys’ room','Boys já termina em s, então acrescentamos apenas o apóstrofo.'],
['Caso genitivo','Como escrever “os brinquedos das crianças”?','The children’s toys','Children é um plural que não termina em s, por isso recebe ’s.'],
['Caso genitivo','Para falar da posse de objetos ou coisas, o material ensina que geralmente usamos:','of','Exemplo: the door of the house.'],
['Caso genitivo','Qual opção significa “a porta da casa”?','The door of the house','Esse é o exemplo apresentado no material.'],
['Caso genitivo','Para o nome Charles, o material aceita:','Charles’s e Charles’','As duas formas aparecem como corretas no material.'],
['Caso genitivo','Se Sarah e John dividem o mesmo apartamento, escrevemos:','Sarah and John’s apartment','Como a posse é dos dois, o ’s aparece depois do último nome.'],
['Revisão','Qual frase explica corretamente a diferença entre my e mine?','My vem com um substantivo; mine pode aparecer sozinho.','Exemplo: my book / The book is mine.']],
'História':[
['Grécia Antiga','A Grécia Antiga era formada por:','várias cidades-estado independentes chamadas pólis','A Grécia Antiga não era um único país. Ela era formada por várias pólis.'],
['Grécia Antiga','Mesmo vivendo em cidades diferentes, os gregos tinham em comum:','língua, religião e costumes culturais','Essas semelhanças ajudavam os gregos a se reconhecer como helenos.'],
['Grécia Antiga','Os gregos passaram a buscar explicações racionais para entender o mundo. Isso ajudou no desenvolvimento da:','filosofia e da ciência','O material destaca a busca de explicações racionais, chamada Logos.'],
['Grécia Antiga','O Partenon era um templo construído em Atenas em homenagem à deusa:','Atena','O Partenon foi dedicado à deusa Atena.'],
['Grécia Antiga','Os Jogos Olímpicos da Grécia Antiga começaram em:','776 a.C., na cidade de Olímpia','O material informa essa data e esse local.'],
['Pólis','Uma pólis era:','uma cidade-estado com suas próprias leis e governo','Cada pólis tinha autonomia e organização própria.'],
['Atenas','Em Atenas, os cidadãos participavam diretamente das decisões políticas. Esse sistema era chamado de:','democracia direta','Atenas é apresentada no material como uma democracia direta.'],
['Esparta','Esparta era conhecida principalmente por sua:','forte organização militar','O material destaca o treinamento militar e a disciplina de Esparta.'],
['Atenas','Em Atenas, quem era considerado cidadão?','homem adulto, livre e nascido em Atenas','Essa é a definição usada no material.'],
['Esparta','Na sociedade espartana, os hilotas eram:','servos que trabalhavam sob o domínio da elite','O material apresenta os hilotas como servos estatais.'],
['Esparta','O Agoge era um sistema usado em Esparta para:','educar e treinar os meninos para a vida militar','O treinamento começava ainda na infância.'],
['Roma Antiga','Segundo o material, a Monarquia Romana durou de:','753 a.C. a 509 a.C.','Essas são as datas apresentadas no material.'],
['Roma Antiga','A República Romana começou depois que:','o último rei etrusco foi retirado do poder','A mudança aconteceu em 509 a.C.'],
['República Romana','Na República Romana, dois importantes órgãos de poder eram:','os cônsules e o Senado','O material destaca os cônsules e o Senado.'],
['Sociedade Romana','Os patrícios eram:','aristocratas e grandes donos de terras','Eles concentravam grande parte do poder político e religioso.'],
['Sociedade Romana','Os plebeus formavam a maior parte da população e incluíam:','comerciantes, artesãos e camponeses','Esses grupos aparecem na descrição dos plebeus.'],
['Direitos dos plebeus','Os Tribunos da Plebe podiam:','impedir decisões que prejudicassem os plebeus usando o veto','O poder de veto era uma proteção conquistada pelos plebeus.'],
['Direitos dos plebeus','A Lei das XII Tábuas foi importante porque:','colocou por escrito leis do direito romano','Ela é apresentada como o primeiro código escrito do direito romano.'],
['Direitos dos plebeus','A Lei Canuleia permitiu:','o casamento entre patrícios e plebeus','Essa foi uma das conquistas dos plebeus.'],
['Direitos dos plebeus','Segundo o material, a Lei Licínia-Sêxtia ajudou os plebeus porque:','garantiu um cônsul plebeu e acabou com a escravidão por dívidas para cidadãos romanos','Essas duas mudanças são atribuídas à lei no material.']],
'Artes':[
['O que é arte','A arte é uma forma que as pessoas usam para:','expressar emoções, ideias e maneiras de ver o mundo','O material apresenta a arte como uma forma de expressão humana.'],
['O que é arte','Uma mesma obra pode ter significados diferentes para pessoas diferentes. Isso é chamado de:','subjetividade','O significado pode variar de acordo com quem observa e com o contexto.'],
['O que é arte','Quando dizemos que uma obra pode atravessar séculos e continuar importante, estamos falando de:','atemporalidade','A arte pode permanecer importante e preservar memórias ao longo do tempo.'],
['O que é arte','A arte também pode fazer as pessoas pensarem sobre assuntos da sociedade. Essa é sua função:','crítica e social','A arte pode provocar reflexões sobre questões políticas, culturais e da vida humana.'],
['Obras de arte','Quem pintou “A Noite Estrelada”?','Vincent van Gogh','O material apresenta Vincent van Gogh como autor da obra.'],
['Obras de arte','A pintura “Guernica”, de Pablo Picasso, mostra:','os horrores da Guerra Civil Espanhola','Esse é o tema apresentado no material.'],
['Arte e cultura','Cultura é o conjunto de:','costumes, crenças, conhecimentos e valores de um grupo','A arte pode mostrar aspectos da cultura de um povo.'],
['Arte e cultura','A identidade cultural ajuda um povo a:','manter ligação com suas raízes e tradições','O material relaciona identidade cultural às raízes e tradições.'],
['Arte e cultura','Dizer que a cultura é dinâmica significa que ela:','muda ao longo do tempo junto com a sociedade','A cultura pode se transformar com o passar do tempo.'],
['Linguagem visual','Na linguagem visual, o ponto é:','a menor unidade usada para construir uma imagem','O material chama o ponto de menor unidade da linguagem visual.'],
['Linguagem visual','Uma linha pode ser entendida como:','uma sequência de pontos que cria direção e contornos','Essa é a explicação apresentada no material.'],
['Linguagem visual','Na arte, uma forma pode ser:','geométrica ou parecida com formas encontradas na natureza','O material diferencia formas geométricas e orgânicas.'],
['Linguagem visual','A cor é percebida por nós por causa:','da luz refletida','Essa é a definição apresentada no material.'],
['Linguagem visual','A textura mostra como uma superfície parece ou é ao toque, por exemplo:','áspera, lisa ou macia','Esses são exemplos de textura apresentados no material.'],
['Pontoilismo','No Pontoilismo, uma pintura é formada principalmente por:','pequenos pontos de cor colocados lado a lado','O material cita Georges Seurat como um dos principais nomes do Pontoilismo.'],
['Linguagens artísticas','Pintura, escultura, fotografia e cinema são exemplos de:','artes visuais','Essas artes são percebidas principalmente pela visão.'],
['Música','Quais são três elementos importantes da música apresentados no material?','melodia, harmonia e ritmo','Esses três elementos aparecem no material.'],
['Dança','Na dança, usamos principalmente:','o corpo, o espaço, o tempo e o movimento','Esses elementos ajudam a comunicar ideias e sentimentos.'],
['Teatro','Uma apresentação de teatro pode ter:','atores, texto, cenário, figurino, iluminação e sons','Esses elementos fazem parte do teatro segundo o material.'],
['Teatro','Na Grécia Antiga, as máscaras usadas pelos atores ajudavam a:','mostrar os personagens de longe e aumentar a voz','O material explica essas duas funções das máscaras.']]};
const wrong={
'Inglês':[['mostrar quando uma ação aconteceu','dar nome a uma pessoa ou objeto','transformar toda palavra em plural'],['um verbo de ação','um artigo definido','uma palavra sem relação com posse'],['colocar sempre a letra s no final','retirar todas as palavras da frase','usar a mesma palavra para qualquer pessoa']],
'História':[['um único reino governado por um rei','uma cidade do Egito Antigo','uma região sem cidades organizadas'],['apenas guerras e batalhas','somente a língua latina','um único governante para todas as cidades'],['um tipo de comércio marítimo','uma festa religiosa romana','uma forma de escrita egípcia']],
'Artes':[['decorar objetos sem transmitir nenhuma ideia','copiar exatamente tudo que existe','servir apenas para vender produtos'],['uma regra que dá o mesmo significado a toda obra','uma técnica usada somente na música','um tipo de material para pintura'],['desaparecer rapidamente da memória','existir apenas no ano em que foi criada','não ter relação com a história']]
};
window.QUESTIONS=[];Object.entries(facts).forEach(([subject,items])=>items.forEach(([topic,stem,correct,explanation],i)=>{let pool=wrong[subject][i%wrong[subject].length];let options=[correct,...pool];let shift=i%4;options=options.slice(shift).concat(options.slice(0,shift));QUESTIONS.push({subject,topic,stem,options,answer:options.indexOf(correct),explanation})}));