const facts={
'Inglês':[
['Adjetivos possessivos','Os adjetivos possessivos, como my, your e her, servem para:','mostrar a quem algo pertence','Pense assim: o adjetivo possessivo responde à ideia de “de quem é?”. Ele vem antes de um nome. Exemplo: my book = meu livro.'],
['Adjetivos possessivos','Complete: “She loves ___ job.”','her','She significa “ela”. Quando algo pertence ou se relaciona a ela, usamos her antes do substantivo: her job.'],
['Adjetivos possessivos','Complete: “We sold ___ car last week.”','our','We significa “nós”. O possessivo correspondente é our. Por isso: our car = nosso carro.'],
['Adjetivos possessivos','Complete: “They forgot ___ passports at home.”','their','They significa “eles/elas”. O possessivo correspondente é their: their passports = os passaportes deles/delas.'],
['Adjetivos possessivos','Na frase “The dog is chasing its tail”, a palavra “its” indica:','que a cauda pertence ao cachorro','Its é usado para indicar posse quando falamos de uma coisa ou animal. Aqui, tail é a cauda do cachorro.'],
['Adjetivos possessivos','Qual possessivo combina com I?','my','I significa “eu”. Antes de um substantivo, usamos my: my pencil, my school, my book.'],
['Adjetivos possessivos','Qual possessivo combina com you?','your','You corresponde a “você/vocês”. Antes de um substantivo, usamos your: your notebook.'],
['Adjetivos possessivos','Qual possessivo combina com he?','his','He significa “ele”. Para indicar algo dele, usamos his: his backpack = a mochila dele.'],
['Adjetivos possessivos','Qual possessivo combina com she?','her','She significa “ela”. Para indicar algo dela, usamos her: her pencil = o lápis dela.'],
['Adjetivos possessivos','Qual possessivo combina com we?','our','We significa “nós”. O possessivo é our: our classroom = nossa sala de aula.'],
['Pronomes possessivos','Os pronomes possessivos, como mine e yours, são usados para:','indicar posse sem repetir o substantivo','Eles evitam repetição. Em vez de dizer “This is my book”, depois podemos dizer apenas “It is mine”.'],
['Pronomes possessivos','Complete: “This jacket is ___, not yours.”','mine','Mine pode aparecer sozinho e substitui “my jacket”. Assim, não precisamos repetir a palavra jacket.'],
['Pronomes possessivos','Na frase “Her house is big, but ours is bigger”, “ours” quer dizer:','our house','Ours substitui “our house”. A frase compara a casa dela com a nossa casa sem repetir house.'],
['Pronomes possessivos','Qual combinação está correta?','My → Mine','My acompanha um substantivo: my book. Mine aparece sozinho: the book is mine.'],
['Pronomes possessivos','Na pergunta “Is it yours?”, a palavra “yours”:','indica posse e pode aparecer sozinha','Yours significa “seu/sua” sem precisar repetir o objeto. Exemplo: Is this pencil yours?'],
['Pronomes possessivos','Qual pronome possessivo corresponde a our?','ours','Our acompanha um nome, como our house. Ours substitui esse conjunto: The house is ours.'],
['Pronomes possessivos','Qual pronome possessivo corresponde a her?','hers','Her acompanha um substantivo: her bag. Hers aparece sozinho: The bag is hers.'],
['Pronomes possessivos','Qual pronome possessivo corresponde a their?','theirs','Their acompanha um substantivo. Theirs pode substituí-lo: their team → theirs.'],
['Pronomes possessivos','Em “I found a phone. Is it yours?”, por que não aparece um substantivo depois de yours?','porque yours já substitui a ideia de “your phone”','Yours é pronome possessivo. Ele já carrega a ideia de posse e evita repetir phone.'],
['Pronomes possessivos','Em “My team won, and theirs lost”, “theirs” substitui:','their team','Theirs evita repetir team. Assim, entendemos que estamos falando do time deles/delas.'],
['Caso genitivo','Para mostrar que algo pertence a uma pessoa, podemos usar:','nome + ’s + objeto','O ’s pode mostrar posse. Exemplo: Peter’s car significa “o carro de Peter”.'],
['Caso genitivo','Como escrever “o carro de Mary” em inglês?','Mary’s car','Mary é uma pessoa no singular. Acrescentamos ’s ao nome: Mary’s car.'],
['Caso genitivo','Quando uma palavra no plural já termina em s, como boys, usamos:','apenas o apóstrofo depois do s','Como boys já termina em s, não colocamos outro s. Escrevemos boys’ room.'],
['Caso genitivo','Como escrever “o quarto dos meninos”?','The boys’ room','Boys é plural terminado em s. Por isso, colocamos apenas o apóstrofo depois dele.'],
['Caso genitivo','Como escrever “os brinquedos das crianças”?','The children’s toys','Children é plural, mas não termina em s. Por isso recebe ’s: children’s toys.'],
['Caso genitivo','Para falar da posse de objetos ou coisas, o material ensina que geralmente usamos:','of','Para coisas, o material prefere of. Exemplo: the door of the house = a porta da casa.'],
['Caso genitivo','Qual opção significa “a porta da casa”?','The door of the house','O material usa esse exemplo para mostrar a construção com of quando falamos de coisas.'],
['Caso genitivo','Para o nome Charles, o material aceita:','Charles’s e Charles’','Como Charles termina em s, o material informa que as duas formas podem ser usadas.'],
['Caso genitivo','Se Sarah e John dividem o mesmo apartamento, escrevemos:','Sarah and John’s apartment','Como o apartamento pertence aos dois juntos, o ’s aparece apenas no último nome: John’s.'],
['Revisão','Qual frase explica corretamente a diferença entre my e mine?','My vem com um substantivo; mine pode aparecer sozinho.','Compare: my book = meu livro. The book is mine = o livro é meu. Essa comparação ajuda a lembrar a diferença.'],
['Revisão','Complete: “I lost ___ keys in the park.”','my','O sujeito é I. O possessivo correspondente é my: my keys = minhas chaves.'],
['Revisão','Complete: “The book is ___.”, indicando que o livro é dela.','hers','Hers é pronome possessivo e pode aparecer sozinho: The book is hers.'],
['Revisão','Em “John left his umbrella, so I gave him his”, o segundo his substitui:','his umbrella','O segundo his evita repetir umbrella. Ele significa “o guarda-chuva dele”.'],
['Revisão','Qual frase usa corretamente um adjetivo possessivo?','Their books are here.','Their é adjetivo possessivo porque vem antes do substantivo books.'],
['Revisão','Qual frase usa corretamente um pronome possessivo?','The books are theirs.','Theirs aparece sozinho e substitui “their books”, por isso é pronome possessivo.'],
['Revisão','Em “my school”, a palavra my vem antes de:','um substantivo','School é um substantivo. Os adjetivos possessivos vêm acompanhados de um substantivo.'],
['Revisão','Em “This pencil is mine”, mine indica que:','o lápis pertence a quem está falando','Mine significa “meu/minha” e aparece sozinho, sem repetir pencil.'],
['Revisão','Qual forma mostra corretamente que o livro pertence a Peter?','Peter’s book','Para uma pessoa no singular, usamos nome + ’s: Peter’s book.'],
['Revisão','Qual forma mostra corretamente uma casa pertencente aos pais?','parents’ house','Parents é plural terminado em s. Por isso, acrescentamos apenas o apóstrofo.'],
['Revisão','Qual ideia une my, your, his, her, our e their?','todas são palavras usadas para indicar posse antes de um substantivo','Essas palavras são adjetivos possessivos. Elas mostram a quem algo pertence e acompanham um nome.']],
'História':[
['Grécia Antiga','A Grécia Antiga era formada por:','várias cidades-estado independentes chamadas pólis','A Grécia Antiga não era um país único como o Brasil de hoje. Ela reunia várias cidades independentes chamadas pólis.'],
['Grécia Antiga','Mesmo vivendo em cidades diferentes, os gregos tinham em comum:','língua, religião e costumes culturais','As pólis eram independentes, mas seus habitantes compartilhavam língua, religião politeísta e costumes. Por isso se reconheciam como helenos.'],
['Grécia Antiga','Os gregos passaram a buscar explicações racionais para entender o mundo. Isso ajudou no desenvolvimento da:','filosofia e da ciência','Em vez de explicar tudo apenas por mitos, alguns gregos buscavam respostas pela razão. O material chama essa busca racional de Logos.'],
['Grécia Antiga','O Partenon era um templo construído em Atenas em homenagem à deusa:','Atena','O Partenon foi construído em Atenas no século V a.C. e dedicado a Atena, deusa ligada à cidade.'],
['Grécia Antiga','Os Jogos Olímpicos da Grécia Antiga começaram em:','776 a.C., na cidade de Olímpia','Os jogos começaram em Olímpia e eram uma celebração religiosa e esportiva em homenagem a Zeus.'],
['Grécia Antiga','Durante os Jogos Olímpicos, a Trégua Sagrada servia para:','interromper guerras e permitir viagens mais seguras até Olímpia','A trégua ajudava atletas e espectadores a viajar com segurança durante os Jogos.'],
['Grécia Antiga','Os gregos chamavam a si mesmos de:','helenos','Mesmo separados em pólis, eles compartilhavam elementos culturais e se identificavam como helenos.'],
['Grécia Antiga','O teatro grego desenvolveu principalmente:','tragédia e comédia','O material cita tragédia e comédia como importantes formas do teatro desenvolvido pelos gregos.'],
['Grécia Antiga','Sócrates, Platão e Aristóteles estão ligados principalmente à:','filosofia grega','Os três aparecem no material como exemplos da importante herança filosófica da Grécia Antiga.'],
['Grécia Antiga','O Partenon é um exemplo importante da:','arquitetura grega','O templo é citado como exemplo da arquitetura grega e de seus padrões de construção.'],
['Pólis','Uma pólis era:','uma cidade-estado com suas próprias leis e governo','Cada pólis tinha sua própria organização política, leis e até moeda.'],
['Atenas','Em Atenas, os cidadãos participavam diretamente das decisões políticas. Esse sistema era chamado de:','democracia direta','Na democracia direta ateniense, os cidadãos participavam das decisões em vez de escolher representantes para tudo.'],
['Esparta','Esparta era conhecida principalmente por sua:','forte organização militar','A educação espartana valorizava disciplina e treinamento militar para formar soldados.'],
['Atenas','Em Atenas, quem era considerado cidadão?','homem adulto, livre e nascido em Atenas','Nem todos os moradores eram cidadãos. O material limita a cidadania aos homens adultos, livres e nascidos em Atenas.'],
['Esparta','Na sociedade espartana, os hilotas eram:','servos que trabalhavam sob o domínio da elite','Os hilotas eram servos estatais submetidos à elite espartana.'],
['Esparta','O Agoge era um sistema usado em Esparta para:','educar e treinar os meninos para a vida militar','O Agoge começava aos 7 anos e buscava preparar os meninos espartíatas para o exército.'],
['Atenas','Atenas valorizava atividades como:','filosofia, artes, oratória e debate público','Essas atividades aparecem no material como parte do foco cultural ateniense.'],
['Esparta','Os espartíatas formavam:','a elite guerreira de Esparta','Eles tinham plenos direitos e ocupavam o topo da sociedade espartana descrita no material.'],
['Esparta','Os periecos eram principalmente:','comerciantes e artesãos livres sem direitos políticos','Eles eram livres, mas não possuíam os mesmos direitos dos espartíatas.'],
['Atenas','Os metecos em Atenas eram:','estrangeiros sem direitos políticos','Os metecos viviam em Atenas, mas não eram considerados cidadãos.'],
['Roma Antiga','Segundo o material, a Monarquia Romana durou de:','753 a.C. a 509 a.C.','Esse é o período indicado no material para a fase em que Roma foi governada por reis.'],
['Roma Antiga','A República Romana começou depois que:','o último rei etrusco foi retirado do poder','Em 509 a.C., a monarquia terminou e Roma passou ao período republicano.'],
['República Romana','Na República Romana, dois importantes órgãos de poder eram:','os cônsules e o Senado','Os cônsules governavam em dupla e o Senado tinha grande importância nas decisões.'],
['Roma Antiga','Segundo a lenda, Roma foi fundada por:','Rômulo','O material conta a lenda de Rômulo e Remo e diz que Rômulo se tornou o primeiro rei.'],
['Roma Antiga','A palavra República, ou Res Publica, significa:','coisa pública','O material apresenta esse significado ao explicar a mudança da Monarquia para a República.'],
['República Romana','Quantos cônsules governavam ao mesmo tempo?','dois','A existência de dois cônsules ajudava a evitar que todo o poder ficasse nas mãos de uma única pessoa.'],
['República Romana','O mandato dos cônsules durava:','um ano','O material informa que os dois cônsules tinham mandato de um ano.'],
['Sociedade Romana','Os patrícios eram:','aristocratas e grandes donos de terras','Eles descendiam das famílias importantes de Roma e concentravam inicialmente poder político e religioso.'],
['Sociedade Romana','Os plebeus formavam a maior parte da população e incluíam:','comerciantes, artesãos e camponeses','Os plebeus trabalhavam, pagavam impostos e tinham deveres militares, mas inicialmente tinham menos direitos políticos.'],
['Sociedade Romana','Os clientes eram:','pessoas ligadas a famílias patrícias em troca de proteção','Eles recebiam proteção econômica e jurídica e, em troca, prestavam serviços e lealdade.'],
['Sociedade Romana','Muitos escravos romanos eram:','prisioneiros de guerra ou pessoas endividadas','O material explica que escravos podiam ser prisioneiros de guerra ou plebeus endividados.'],
['Direitos dos plebeus','Os Tribunos da Plebe podiam:','impedir decisões que prejudicassem os plebeus usando o veto','O veto permitia aos tribunos barrar decisões dos patrícios que prejudicassem a plebe.'],
['Direitos dos plebeus','A Lei das XII Tábuas foi importante porque:','colocou por escrito leis do direito romano','Com as leis escritas e públicas, os patrícios tinham menos liberdade para interpretá-las apenas em benefício próprio.'],
['Direitos dos plebeus','A Lei Canuleia permitiu:','o casamento entre patrícios e plebeus','Essa lei, de 445 a.C., permitiu legalmente o casamento entre os dois grupos.'],
['Direitos dos plebeus','Segundo o material, a Lei Licínia-Sêxtia ajudou os plebeus porque:','garantiu um cônsul plebeu e acabou com a escravidão por dívidas para cidadãos romanos','A lei ampliou os direitos da plebe e garantiu sua presença em um dos cargos de cônsul.'],
['Direitos dos plebeus','Por que as paralisações dos plebeus pressionavam os patrícios?','porque os plebeus eram importantes para o trabalho e para o exército','Quando os plebeus se retiravam, Roma ficava com menos trabalhadores, soldados e suprimentos, pressionando os patrícios a negociar.'],
['Direitos dos plebeus','O Tribunato da Plebe foi criado em:','494 a.C.','O material apresenta 494 a.C. como a data da criação dos magistrados que defendiam os interesses da plebe.'],
['Direitos dos plebeus','A Lei das XII Tábuas é datada no material de:','450 a.C.','Essa lei é apresentada como o primeiro código escrito do direito romano.'],
['Direitos dos plebeus','A Lei Canuleia é datada no material de:','445 a.C.','Ela ficou marcada pela permissão do casamento legal entre patrícios e plebeus.'],
['Direitos dos plebeus','A Lei Licínia-Sêxtia é datada no material de:','367 a.C.','O material relaciona essa lei a importantes conquistas políticas e sociais da plebe.']],
'Artes':[
['O que é arte','A arte é uma forma que as pessoas usam para:','expressar emoções, ideias e maneiras de ver o mundo','A arte comunica. Por meio de imagens, sons, movimentos ou outras formas, as pessoas podem mostrar sentimentos, ideias e visões de mundo.'],
['O que é arte','Uma mesma obra pode ter significados diferentes para pessoas diferentes. Isso é chamado de:','subjetividade','Subjetividade significa que cada pessoa pode perceber uma obra de maneira diferente, dependendo também do contexto.'],
['O que é arte','Quando dizemos que uma obra pode atravessar séculos e continuar importante, estamos falando de:','atemporalidade','Uma obra pode continuar sendo conhecida e estudada muito tempo depois de ter sido criada, ajudando a preservar a memória humana.'],
['O que é arte','A arte também pode fazer as pessoas pensarem sobre assuntos da sociedade. Essa é sua função:','crítica e social','Uma obra pode chamar atenção para problemas e fazer o público refletir sobre temas políticos, culturais e humanos.'],
['Obras de arte','Quem pintou “A Noite Estrelada”?','Vincent van Gogh','Van Gogh criou A Noite Estrelada em 1889. O material destaca o uso expressivo de linhas e cores para transmitir sentimentos.'],
['Obras de arte','A pintura “Guernica”, de Pablo Picasso, mostra:','os horrores da Guerra Civil Espanhola','Picasso usou Guernica para representar o sofrimento e os horrores ligados à Guerra Civil Espanhola.'],
['Arte e cultura','Cultura é o conjunto de:','costumes, crenças, conhecimentos e valores de um grupo','Cultura inclui modos de viver e pensar de um grupo. A arte pode tornar esses elementos visíveis por imagens, sons e gestos.'],
['Arte e cultura','A identidade cultural ajuda um povo a:','manter ligação com suas raízes e tradições','As tradições, costumes e manifestações artísticas ajudam um grupo a reconhecer e preservar sua história.'],
['Arte e cultura','Dizer que a cultura é dinâmica significa que ela:','muda ao longo do tempo junto com a sociedade','A cultura não fica parada: costumes e formas de expressão podem se transformar quando a sociedade muda.'],
['Arte e cultura','O Festival de Parintins mistura principalmente:','teatro, música e dança','O Boi-Bumbá de Parintins é citado como exemplo brasileiro de manifestação cultural que reúne diferentes linguagens artísticas.'],
['Arte e cultura','O Samba de Roda do Recôncavo Baiano foi reconhecido pela UNESCO como:','Patrimônio Cultural Imaterial da Humanidade','O material destaca esse reconhecimento por causa da importância histórica e cultural do Samba de Roda.'],
['Arte e cultura','A diversidade cultural significa que a cultura:','pode variar conforme a região, a época e a sociedade','Povos e lugares diferentes podem desenvolver costumes e formas de arte diferentes. Isso faz parte da diversidade cultural.'],
['Linguagem visual','Na linguagem visual, o ponto é:','a menor unidade usada para construir uma imagem','O ponto é o elemento visual mais simples. Muitos pontos juntos podem formar linhas, formas e imagens.'],
['Linguagem visual','Uma linha pode ser entendida como:','uma sequência de pontos que cria direção e contornos','A linha pode guiar nossos olhos pela imagem e também formar os contornos dos desenhos.'],
['Linguagem visual','Na arte, uma forma pode ser:','geométrica ou parecida com formas encontradas na natureza','Quadrados e círculos são formas geométricas. Formas inspiradas na natureza são chamadas de orgânicas.'],
['Linguagem visual','A cor é percebida por nós por causa:','da luz refletida','O material explica a cor como percepção da luz refletida e também apresenta cores primárias, secundárias, quentes e frias.'],
['Linguagem visual','A textura mostra como uma superfície parece ou é ao toque, por exemplo:','áspera, lisa ou macia','A textura pode ser percebida pelo toque ou apenas visualmente em uma imagem.'],
['Linguagem visual','Uma imagem é formada pela combinação de elementos como:','ponto, linha, forma, cor e textura','Esses elementos funcionam como peças usadas para construir uma imagem.'],
['Pontoilismo','No Pontoilismo, uma pintura é formada principalmente por:','pequenos pontos de cor colocados lado a lado','No Pontoilismo, o artista cria a imagem usando muitos pequenos pontos de cor. Georges Seurat é citado como um importante nome desse movimento.'],
['Pontoilismo','Qual artista é citado como líder do Pontoilismo?','Georges Seurat','O material relaciona Georges Seurat ao Pontoilismo e cita Uma Tarde de Domingo na Ilha de Grande Jatte.'],
['Linguagens artísticas','Pintura, escultura, fotografia e cinema são exemplos de:','artes visuais','Elas são chamadas de artes visuais porque são apreciadas principalmente pela visão.'],
['Artes visuais','As artes visuais podem usar elementos como:','espaço, luz, cor e volume','Esses elementos aparecem no material como características importantes das artes visuais.'],
['Artes visuais','Uma escultura pode ser considerada uma obra:','tridimensional','Uma obra tridimensional possui volume e ocupa espaço, como acontece com muitas esculturas.'],
['Artes visuais','“O Pensador” é uma escultura de:','Auguste Rodin','O material apresenta O Pensador como exemplo de obra das artes visuais.'],
['Música','Quais são três elementos importantes da música apresentados no material?','melodia, harmonia e ritmo','Melodia é uma combinação de sons; harmonia envolve sons simultâneos; ritmo organiza o tempo musical.'],
['Música','A música é a arte de combinar:','sons e silêncio ao longo do tempo','O silêncio também faz parte da organização musical. Junto com os sons, ele ajuda a construir a música.'],
['Música','Na música, ritmo está relacionado principalmente:','ao tempo','O ritmo organiza a duração e a sequência dos sons no tempo.'],
['Música','Na música, harmonia está relacionada a:','sons tocados ao mesmo tempo','O material define harmonia como sons simultâneos, isto é, que acontecem juntos.'],
['Música','Na música, melodia é:','uma combinação de sons','A melodia é uma sequência ou combinação de sons que podemos reconhecer em uma música.'],
['Dança','Na dança, usamos principalmente:','o corpo, o espaço, o tempo e o movimento','A dança usa o corpo em movimento para comunicar intenções e sentimentos, normalmente com organização no espaço e no tempo.'],
['Dança','Frevo, hip-hop e O Lago dos Cisnes aparecem no material como exemplos de:','dança','São exemplos diferentes de dança, mostrando que essa linguagem artística pode assumir muitas formas.'],
['Teatro','Uma apresentação de teatro pode ter:','atores, texto, cenário, figurino, iluminação e sons','O teatro reúne vários elementos para contar uma história diante do público. A sonoplastia corresponde aos sons usados na apresentação.'],
['Teatro','Na Grécia Antiga, as máscaras usadas pelos atores ajudavam a:','mostrar os personagens de longe e aumentar a voz','As máscaras, chamadas personas, ajudavam o público a reconhecer personagens e também funcionavam como amplificadores da voz.'],
['Teatro','O teatro é uma linguagem artística baseada principalmente em:','representar histórias diante de um público','A atuação é central no teatro, mas cenário, figurino, iluminação, texto e sons também ajudam a contar a história.'],
['Teatro','“Auto da Compadecida”, de Ariano Suassuna, aparece como exemplo de:','obra teatral','O material cita a peça como exemplo da linguagem artística do teatro.'],
['Revisão','Qual linguagem artística usa principalmente o corpo e o movimento?','dança','Na dança, o corpo é o principal meio de expressão, organizado no espaço e no tempo.'],
['Revisão','Qual linguagem artística organiza sons e silêncio ao longo do tempo?','música','A música combina sons e silêncio e trabalha elementos como melodia, harmonia e ritmo.'],
['Revisão','Qual elemento visual pode ser áspero, liso ou macio?','textura','Essas palavras descrevem características táteis ou visuais de uma superfície.'],
['Revisão','Qual elemento visual pode formar contornos e indicar direção?','linha','A linha é uma sequência de pontos e pode guiar o olhar dentro de uma imagem.'],
['Revisão','Qual elemento visual é considerado o início de qualquer forma?','ponto','O ponto é apresentado como a menor unidade da linguagem visual e pode dar início à construção de formas.']]};
const wrong={
'Inglês':['mostrar quando uma ação aconteceu','indicar apenas o plural de uma palavra','ser sempre um verbo','dar nome a uma pessoa ou lugar','indicar uma pergunta','mostrar somente o tempo passado'],
'História':['um único reino governado por um faraó','uma característica do Egito Antigo','uma atividade sem relação com o tema','um cargo existente apenas em Atenas','uma lei criada na Grécia','uma tradição artística moderna'],
'Artes':['uma regra de matemática','um acontecimento político romano','uma técnica usada apenas para escrever textos','um tipo de governo da Antiguidade','uma atividade sem relação com expressão artística','um conceito exclusivo da História']
};
window.QUESTIONS=[];Object.entries(facts).forEach(([subject,items])=>items.forEach(([topic,stem,correct,explanation],i)=>{let pool=wrong[subject];let distractors=[pool[i%pool.length],pool[(i+2)%pool.length],pool[(i+4)%pool.length]];let options=[correct,...distractors];let shift=i%4;options=options.slice(shift).concat(options.slice(0,shift));QUESTIONS.push({subject,topic,stem,options,answer:options.indexOf(correct),explanation})}));